### ISSUE TITLE
Feature request - Specify Bedrock model id when creating API key

### ISSUE THREAD

**Issue by ensean** [aws-samples/sample-connector-for-bedrock#2]
If BRconnector supports specify Bedrock model id when creating API key, it will be more convenient to switch among the rich models bedrock provided

**Comment by cloudbeer** [comment]
Yes, the next release will support API Key grouping, and different models can be used by different groups. All of these can be maintained in the manager webui.

**Comment by cloudbeer** [comment]
Model isolation can now be supported since 0.0.5. You can set it up in the management backend /manager.

- You can set up models in group management, and an API Key can belong to a certain group.

- You can also set up models in API Key management.

The models set up in these two ways are additive..
